// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJJIdsX1mMvHjemJWMUTM9e-LKyxIKyQ',
    appId: '1:101546109188:web:91dcdd517ebe3eed90c851',
    messagingSenderId: '101546109188',
    projectId: 'posturight-d18ad',
    authDomain: 'posturight-d18ad.firebaseapp.com',
    databaseURL: 'https://posturight-d18ad-default-rtdb.firebaseio.com/',
    storageBucket: 'posturight-d18ad.appspot.com',
    measurementId: 'G-Z0T7LFS95W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMNsmn_ybWji42v6edCEBCZ4fpS00loQc',
    appId: '1:101546109188:android:c4cfefc1367d391490c851',
    messagingSenderId: '101546109188',
    projectId: 'posturight-d18ad',
    databaseURL: 'https://posturight-d18ad-default-rtdb.firebaseio.com/',
    storageBucket: 'posturight-d18ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5HGRygXDychSWQredccm7VsZelKZ2ks',
    appId: '1:101546109188:ios:63e0847aa4b921f390c851',
    messagingSenderId: '101546109188',
    projectId: 'posturight-d18ad',
    databaseURL: 'https://posturight-d18ad-default-rtdb.firebaseio.com/',
    storageBucket: 'posturight-d18ad.appspot.com',
    iosClientId: '101546109188-lg4vm62qdbsruio84b1cj491pl47i2k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.posturight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy5HGRygXDychSWQredccm7VsZelKZ2ks',
    appId: '1:101546109188:ios:63e0847aa4b921f390c851',
    messagingSenderId: '101546109188',
    projectId: 'posturight-d18ad',
    storageBucket: 'posturight-d18ad.appspot.com',
    iosClientId: '101546109188-lg4vm62qdbsruio84b1cj491pl47i2k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.posturight',
  );
}
